<form class="form-signin" method="post" action="">
	<h2 class="form-signin-heading">Jelentkezz be</h2>
	<label for="inputEmail" class="sr-only">Email cím</label>
	<input type="email" id="inputEmail" class="form-control" placeholder="Email cím" required autofocus>
	<label for="inputPassword" class="sr-only">Jelszó</label>
	<input type="password" id="inputPassword" class="form-control" placeholder="Jelszó" required>
	<button class="btn btn-lg btn-primary btn-block" type="submit">Bejelentkezés</button>
	<button class="btn btn-lg btn-link btn-block" type="submit">Regisztráció</button>
</form>