<form class="form-signin" method="post" action="<?=$this->url->get('/user/registration')?>">
	<?=$this->getContent()?>
	<h2 class="form-signin-heading">Register new account</h2>
	<label for="inputName" class="sr-only">Full name</label>
	<input type="text" name="name" id="inputName" class="form-control" placeholder="Full name" required autofocus>
	<label for="inputEmail" class="sr-only">Email address</label>
	<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
	<label for="inputPassword" class="sr-only">Password</label>
	<input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
	<label for="inputPasswordVerify" class="sr-only">Password Verify</label>
	<input type="password" name="passwordVerify" id="inputPasswordVerify" class="form-control" placeholder="Password verify" required>
	<button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
	<a href="<?=$this->url->get('/user/login')?>" class="btn btn-lg btn-link btn-block" title="Login">Have an account? Login!</a>
</form>